/**:
    ros__parameters:
        # reconstructKdTree: true       # not present in original working mid360 config
        # updateState: true             # not present in original working mid360 config
        # updateFrequency: 30           # not present in original working mid360 config
        max_iteration: 3
        map_file_path: "./test.pcd"
        filter_size_corner: 0.5
        filter_size_surf: 0.5
        filter_size_map: 0.5
        cube_side_length: 1000.0
        point_filter_num: 3
        feature_extract_enable: false
        debug_mode_enable: false
        pcd_save_enable: false
        visualize_map: true

        common:
            lid_topic:  "/livox/lidar"
            imu_topic:  "/livox/imu"
            time_sync_en: false         # ONLY turn on when external time synchronization is really not possible

        preprocess:
            lidar_type: 1                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
            scan_line: 4
            blind: 4.0

        mapping:
            det_range:     70.0
            fov_degree:    360.0
            gyr_cov: 0.1
            acc_cov: 0.1
            b_gyr_cov: 0.0001
            b_acc_cov: 0.0001
            extrinsic_T: [ -0.011, -0.02329, 0.04412 ]
            extrinsic_R: [ 1., 0., 0.,
                            0., 1., 0.,
                            0., 0., 1.]

        publish:
            scan_publish_en:  true       # false: close all the point cloud output
            dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
            scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame
